apiVersion: apps/v1
kind: Deployment
metadata:
  name: ux-backend-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ux-backend-server
      app.kubernetes.io/component: ux-backend-server
      app.kubernetes.io/name: ux-backend-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ux-backend-server
        app.kubernetes.io/component: ux-backend-server
        app.kubernetes.io/name: ux-backend-server
    spec:
      containers:
      - command:
        - /usr/local/bin/ux-backend-server
        env:
        - name: ONBOARDING_TOKEN_LIFETIME
        - name: UX_BACKEND_PORT
        - name: TLS_ENABLED
        image: controller
        imagePullPolicy: Always
        name: ux-backend-server
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /etc/private-key
          name: onboarding-private-key
        - mountPath: /etc/tls/private
          name: ux-cert-secret
      - args:
        - -provider=openshift
        - -https-address=
        - -http-address=:8888
        - -email-domain=*
        - -upstream=http://localhost:8080/
        - -tls-cert=/etc/tls/private/tls.crt
        - -tls-key=/etc/tls/private/tls.key
        - -cookie-secret-file=/etc/proxy/secrets/session_secret
        - -openshift-service-account=ocs-operator-ux-backend-server
        - -openshift-delegate-urls={"/":{"group":"ocs.openshift.io","resource":"storageclusters","namespace":"openshift-storage","verb":"create"}}
        - -openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        image: quay.io/openshift/origin-oauth-proxy:latest
        imagePullPolicy: Always
        name: oauth-proxy
        ports:
        - containerPort: 8888
        resources: {}
        volumeMounts:
        - mountPath: /etc/proxy/secrets
          name: ux-proxy-secret
        - mountPath: /etc/tls/private
          name: ux-cert-secret
      serviceAccountName: ux-backend-server
      tolerations:
      - effect: NoSchedule
        key: node.ocs.openshift.io/storage
        operator: Equal
        value: "true"
      volumes:
      - name: onboarding-private-key
        secret:
          optional: true
          secretName: onboarding-private-key
      - name: ux-proxy-secret
        secret:
          secretName: ux-backend-proxy
      - name: ux-cert-secret
        secret:
          secretName: ux-cert-secret

