apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: v1.24
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: v1.24
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: v1.24
    security.openshift.io/scc.podSecurityLabelSync: "false"
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  labels:
    operator: ocs
    app.kubernetes.io/name: ocs
    app.kubernetes.io/component: operator
spec:
  selector:
    matchLabels:
      operator: ocs
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        operator: ocs
        app.kubernetes.io/name: ocs
        app.kubernetes.io/component: operator
    spec:
      serviceAccountName: controller-manager
      containers:
      - command:
        - ocs-operator
        args:
        - --enable-leader-election
        - "--health-probe-bind-address=:8081"
        image: controller
        imagePullPolicy: Always
        name: ocs-operator
        env:
          - name: SINGLE_NODE
            value: "true"
          - name: SKIP_NOOBAA_CRD_WATCH
            value: "true"
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: OCS_METRICS_EXPORTER_IMAGE
            value: quay.io/jarrpa/ocs-metrics-exporter:rns-dev
          - name: ROOK_CEPH_IMAGE
            value: docker.io/rook/ceph:v1.13.5
          - name: CEPH_IMAGE
            value: quay.io/ceph/ceph:v18.2.0
          - name: NOOBAA_CORE_IMAGE
            value: quay.io/noobaa/noobaa-core:master-20240108
          - name: NOOBAA_DB_IMAGE
            value: centos/postgresql-12-centos8
          - name: PROVIDER_API_SERVER_IMAGE
            value: quay.io/jarrpa/ocs-operator:rns-dev
          - name: ONBOARDING_VALIDATION_KEYS_GENERATOR_IMAGE
            value: quay.io/jarrpa/ocs-operator:rns-dev
          - name: OPERATOR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
              drop:
              - all
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /etc/private-key
          name: onboarding-private-key
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsNonRoot: true
      volumes:
      - name: onboarding-private-key
        secret:
          # this is marked as optional as the secret gets created only in provider mode
          optional: true
          secretName: onboarding-private-key
