apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: v1.24
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: v1.24
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: v1.24
    security.openshift.io/scc.podSecurityLabelSync: "false"
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  selector:
    matchLabels:
      name: controller-manager
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: controller-manager
    spec:
      serviceAccountName: controller-manager
      containers:
      - command:
        - ocs-operator
        args:
        - --enable-leader-election
        - "--health-probe-bind-address=:8081"
        image: controller
        imagePullPolicy: Always
        name: ocs-operator
        env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: ROOK_CEPH_IMAGE
            value: docker.io/rook/ceph:v1.12.2
          - name: CEPH_IMAGE
            value: quay.io/ceph/ceph:v17
          - name: NOOBAA_CORE_IMAGE
            value: quay.io/noobaa/noobaa-core:master-20230718
          - name: NOOBAA_DB_IMAGE
            value: centos/postgresql-12-centos8
          - name: PROVIDER_API_SERVER_IMAGE
            value: quay.io/jarrpa/ocs-operator:latest
          - name: OPERATOR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
              drop:
                - all
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsNonRoot: true
