---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-example-pvc-cephfs
  labels:
    app: example-nginx-pvc-cephfs
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: example-pvc-cephfs
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: task-pv-storage
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: example-nginx-pvc-cephfs
  name: nginx-example-pvc-cephfs
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: example-nginx-pvc-cephfs
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: example-nginx-pvc-cephfs
  name: nginx-example-pvc-cephfs
spec:
  host: nginx-example-pvc-cephfs-ocs-operator-system.apps.sno-dev.jarrpa.dev
  port:
    targetPort: 80
  to:
    kind: Service
    name: nginx-example-pvc-cephfs
    weight: 100
  wildcardPolicy: None
