---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-consumer-pvc-cephfs
  namespace: ocs-client-operator-system
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: consumer-pvc-cephfs
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: /mnt
          name: task-pv-storage
