---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-example-pvc-cephfs
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: example-pvc-cephfs
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: /mnt
          name: task-pv-storage
      securityContext:
        runAsNonRoot: true
