---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  generateName: example-pvc-cephfs
  name: example-pvc-cephfs
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: example-storagecluster-cephfs
  volumeMode: Filesystem
