---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: upgrade-testing
  generateName: example-pvc-rbd
  name: example-pvc-rbd
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: example-storagecluster-ceph-rbd
  volumeMode: Filesystem
