---
apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
  namespace: ocs-client-operator-system
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: test-medium-0-pvc
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeDevices:
        - devicePath: /dev/block
          name: task-pv-storage
