---
apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  annotations:
    uninstall.ocs.openshift.io/cleanup-policy: delete
    uninstall.ocs.openshift.io/mode: graceful
  name: ocs-storagecluster
  namespace: openshift-storage
spec:
  allowRemoteStorageConsumers: true
  arbiter: {}
  encryption:
    kms: {}
  externalStorage: {}
  hostNetwork: true
  labelSelector: {}
  managedResources:
    cephBlockPools:
      disableSnapshotClass: true
      disableStorageClass: true
      reconcileStrategy: ignore
    cephCluster: {}
    cephConfig: {}
    cephDashboard: {}
    cephFilesystems:
      disableSnapshotClass: true
      disableStorageClass: true
    cephObjectStoreUsers: {}
    cephObjectStores: {}
    cephToolbox: {}
  mirroring: {}
  multiCloudGateway:
    reconcileStrategy: ignore
  defaultStorageProfile: "medium-performance-storageprofile"
  storageProfiles:
    - name: medium
      deviceClass: medium
  backingStorageClasses:
    - metadata:
        name: medium-performance
      provisioner: ebs.csi.aws.com
      parameters:
        type: gp3
        iops: "6000"
  resources:
    mds: {}
    mgr: {}
    mon: {}
    nfs: {}
    noobaa-core: {}
    noobaa-db: {}
    noobaa-endpoint: {}
    rgw: {}
  storageDeviceSets:
  - config: {}
    count: 1
    deviceClass: medium
    dataPVCTemplate:
      metadata: {}
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 4Ti
        storageClassName: medium-performance
        volumeMode: Block
      status: {}
    name: default
    placement: {}
    portable: true
    preparePlacement: {}
    replica: 3
    resources: {}
