#!/usr/bin/env bash

set -e

source hack/common.sh
source hack/docker-common.sh

DEFAULT_VOLUME_MIGRATION_IMAGE_NAME="ocs-volume-migration"
VOLUME_MIGRATION_IMAGE_NAME="${VOLUME_MIGRATION_IMAGE_NAME:-${DEFAULT_VOLUME_MIGRATION_IMAGE_NAME}}"
DEFAULT_VOLUME_MIGRATION_FULL_IMAGE_NAME="${IMAGE_REGISTRY}/${REGISTRY_NAMESPACE}/${VOLUME_MIGRATION_IMAGE_NAME}:${IMAGE_TAG}"
VOLUME_MIGRATION_FULL_IMAGE_NAME="${VOLUME_MIGRATION_FULL_IMAGE_NAME:-${DEFAULT_VOLUME_MIGRATION_FULL_IMAGE_NAME}}"

${IMAGE_BUILD_CMD} build -f tools/volume-migration/Dockerfile -t "${VOLUME_MIGRATION_FULL_IMAGE_NAME}" . \
    --build-arg="GOOS=${GOOS}" --build-arg="GOARCH=${GOARCH}" --build-arg="LDFLAGS=${LDFLAGS}"
