apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: example-storagecluster
spec:
  enableCephTools: true
  labelSelector: {}
  manageNodes: false
  multiCloudGateway:
    reconcileStrategy: ignore
  resources:
    mds: {}
    mgr: {}
    mon: {}
    nfs: {}
    noobaa-core: {}
    noobaa-db: {}
    noobaa-endpoint: {}
    rgw: {}
  storageDeviceSets:
  - name: example-deviceset
    count: 1
    replica: 3
    resources: {}
    placement: {}
    dataPVCTemplate:
      spec:
        storageClassName: gp3-csi
        accessModes:
        - ReadWriteOnce
        volumeMode: Block
        resources:
          requests:
            storage: 1Ti
    portable: true
